### ISSUE TITLE
Error inflating class ir.hamsaa.RtlMaterialSpinner

### ISSUE THREAD

**Issue by RehamAbdelazime** [hamsaadev/RTLMaterialSpinner#6]
Here's the log

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.developer.test, PID: 4631
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.developer.test/com.example.developer.test.MainActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class ir.hamsaa.RtlMaterialSpinner
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                   Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class ir.hamsaa.RtlMaterialSpinner
                   Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class ir.hamsaa.RtlMaterialSpinner
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Constructor.newInstance0(Native Method)
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:647)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                      at com.example.developertest.MainActivity.onCreate(MainActivity.java:11)
                      at android.app.Activity.performCreate(Activity.java:6975)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                   Caused by: java.lang.RuntimeException: Font asset not found typeface.ttf
                      at android.graphics.Typeface.createFromAsset(Typeface.java:784)
                      at ir.hamsaa.RtlMaterialSpinner.initAttributes(RtlMaterialSpinner.java:186)
                      at ir.hamsaa.RtlMaterialSpinner.init(RtlMaterialSpinner.java:140)
                      at ir.hamsaa.RtlMaterialSpinner.<init>(RtlMaterialSpinner.java:120)
                      at java.lang.reflect.Constructor.newInstance0(Native Method) 
                      at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
                      at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                      at com.example.developer.test.MainActivity.onCreate(MainActivity.java:11) 
                      at android.app.Activity.performCreate(Activity.java:6975) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                      at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                      at android.os.Handler.dispatchMessage(Handler.java:105) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6541) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 

ok fixed by removing the type face attribute but when i set isRTl to true the arrow disappears

**Comment by mihodihasan** [comment]
Facing the same issue
